name: ğŸš€ Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # permite ejecutarlo manualmente desde la pestaÃ±a Actions

permissions:
  contents: write # necesario para poder subir a gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # versiÃ³n LTS recomendada

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ—ï¸ Build Angular project
        run: |
          npm run build -- --configuration production --base-href /whatsapplink/

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages            # rama destino
          folder: dist/whatsapplink   # carpeta generada por el build
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
